-- AlterTable
DO $$ BEGIN
  CREATE TYPE "EventCategory" AS ENUM ('COMPETITION', 'CONFERENCE', 'EXHIBITION', 'GENERAL');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "category" "EventCategory" NOT NULL DEFAULT 'GENERAL';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "photoUrl" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "pdfUrl" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "registrationDeadline" TIMESTAMP(3);
