"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Card } from "@/components/ui/card";

interface SlipLogRow {
  id: string; period: string; createdAt: string;
  employee: { id: string; fullName: string; staffProfile: { employeeNo: string } | null };
  generatedBy: { id: string; fullName: string };
}

function fmtDateTime(s: string) {
  return new Date(s).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
}

export default function SalarySlipLogPage() {
  const [rows, setRows] = useState<SlipLogRow[]>([]);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");

  useEffect(() => {
    api<SlipLogRow[]>("/employees/salary-slip-log")
      .then((r) => { setRows(r); setState("ready"); })
      .catch(() => setState("error"));
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <p className="text-xs font-medium uppercase tracking-widest text-slate-400">HR</p>
        <h1 className="font-display text-2xl font-semibold text-night dark:text-white">Salary Slip Log</h1>
        <p className="mt-1 text-sm text-slate-500">Every salary slip generated — who printed it, for whom, and when.</p>
      </div>

      <Card className="p-0 overflow-hidden">
        {state === "error" && (
          <p className="p-6 text-sm text-slate-500">
            Couldn&apos;t reach the API. Start it with <code>docker compose up</code>, then reload.
          </p>
        )}
        {state === "ready" && rows.length === 0 && (
          <p className="p-6 text-sm text-slate-500">No salary slips generated yet.</p>
        )}
        {rows.length > 0 && (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="text-left text-xs uppercase tracking-wide text-slate-400">
                <tr className="border-b border-slate-100 dark:border-white/5">
                  <th className="px-4 py-3 font-medium">Employee</th>
                  <th className="px-4 py-3 font-medium">Employee No.</th>
                  <th className="px-4 py-3 font-medium">Pay Period</th>
                  <th className="px-4 py-3 font-medium">Generated By</th>
                  <th className="px-4 py-3 font-medium">Generated At</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((row) => (
                  <tr key={row.id} className="border-b border-slate-50 last:border-0 dark:border-white/5">
                    <td className="px-4 py-3 font-medium text-night dark:text-white">{row.employee.fullName}</td>
                    <td className="px-4 py-3 text-slate-500">{row.employee.staffProfile?.employeeNo ?? "—"}</td>
                    <td className="px-4 py-3 text-slate-500">{row.period}</td>
                    <td className="px-4 py-3 text-slate-500">{row.generatedBy.fullName}</td>
                    <td className="px-4 py-3 text-slate-500">{fmtDateTime(row.createdAt)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
