"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

interface CertificateLogRow {
  id: string; refNo: string | null; createdAt: string; hasDocument: boolean;
  employee: { id: string; fullName: string; staffProfile: { employeeNo: string } | null };
  generatedBy: { id: string; fullName: string };
}

function fmtDateTime(s: string) {
  return new Date(s).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
}

export default function SalaryCertificateLogPage() {
  const [rows, setRows] = useState<CertificateLogRow[]>([]);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [openingId, setOpeningId] = useState<string | null>(null);

  useEffect(() => {
    api<CertificateLogRow[]>("/employees/salary-certificate-log")
      .then((r) => { setRows(r); setState("ready"); })
      .catch(() => setState("error"));
  }, []);

  async function openDocument(id: string) {
    setOpeningId(id);
    try {
      const { url } = await api<{ url: string }>(`/employees/salary-certificate-log/${id}/download`);
      window.open(url, "_blank");
    } catch {
      // Signed-URL fetch failures surface via the disabled button state below; nothing else to do here.
    } finally {
      setOpeningId(null);
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <p className="text-xs font-medium uppercase tracking-widest text-slate-400">HR</p>
        <h1 className="font-display text-2xl font-semibold text-night dark:text-white">Salary Certificate Log</h1>
        <p className="mt-1 text-sm text-slate-500">Every salary certificate generated — who printed it, for whom, and when.</p>
      </div>

      <Card className="p-0 overflow-hidden">
        {state === "error" && (
          <p className="p-6 text-sm text-slate-500">
            Couldn&apos;t reach the API. Start it with <code>docker compose up</code>, then reload.
          </p>
        )}
        {state === "ready" && rows.length === 0 && (
          <p className="p-6 text-sm text-slate-500">No salary certificates generated yet.</p>
        )}
        {rows.length > 0 && (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="text-left text-xs uppercase tracking-wide text-slate-400">
                <tr className="border-b border-slate-100 dark:border-white/5">
                  <th className="px-4 py-3 font-medium">Employee</th>
                  <th className="px-4 py-3 font-medium">Employee No.</th>
                  <th className="px-4 py-3 font-medium">Ref No.</th>
                  <th className="px-4 py-3 font-medium">Generated By</th>
                  <th className="px-4 py-3 font-medium">Generated At</th>
                  <th className="px-4 py-3 text-right font-medium">Document</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((row) => (
                  <tr key={row.id} className="border-b border-slate-50 last:border-0 dark:border-white/5">
                    <td className="px-4 py-3 font-medium text-night dark:text-white">{row.employee.fullName}</td>
                    <td className="px-4 py-3 text-slate-500">{row.employee.staffProfile?.employeeNo ?? "—"}</td>
                    <td className="px-4 py-3 text-slate-500">{row.refNo ?? "—"}</td>
                    <td className="px-4 py-3 text-slate-500">{row.generatedBy.fullName}</td>
                    <td className="px-4 py-3 text-slate-500">{fmtDateTime(row.createdAt)}</td>
                    <td className="px-4 py-3 text-right">
                      {row.hasDocument ? (
                        <Button variant="ghost" onClick={() => openDocument(row.id)} disabled={openingId === row.id}>
                          {openingId === row.id ? "Opening…" : "View / Download"}
                        </Button>
                      ) : (
                        <span className="text-xs text-slate-400">Not available</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
